name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main   # или master, или свою ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.-Bsid4mJI2Bz9olZuHsa9hkabuF0swnjf67T8JFm }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.114cac2a6d788a06db81f5ca4e797f75 }}
        run: |
          wrangler deploy
